BSATroop829/Controllers/GalleryController.cs
using BSATroop829.Data;
using BSATroop829.Models;
using Microsoft.AspNetCore.Mvc;

namespace BSATroop829.Controllers
{
    public class GalleryController : Controller
    {
        ApplicationDbContext db;
        public GalleryController(ApplicationDbContext db)
        {
            this.db = db;

        }
        public IActionResult Index()
        {
            GalleryViewModel viewModel = new GalleryViewModel();
            viewModel.PhotosList = db.PhotoGallery.ToList();
            viewModel.Photos = new PhotoGalleryVeiwModel();
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult AddPhotos(GalleryViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var Files = model.Photos.PhotoFile;

            if (Files.Count > 0)
            {
                foreach (var item in Files)
                {
                    PhotoGalleryVeiwModel photography = new PhotoGalleryVeiwModel();
                    var guid = Guid.NewGuid().ToString();
                    var filePath = "wwwroot/Resources/" + guid + item.FileName;
                    var fileName = guid + item.FileName;
                    using (var stream = System.IO.File.Create(filePath))
                    {
                        item.CopyTo(stream);
                        photography.Name = fileName;
                        photography.Path = filePath;
                        photography.Title = item.FileName;
                        photography.NoOfViews = 1;
                        db.PhotoGallery.Add(photography);
                        db.SaveChanges();
                    }
                }
                return RedirectToAction("Index");
            }


            return RedirectToAction("Index");
        }
        
        public IActionResult DeletePhoto(int id)
        {
            var photo = db.PhotoGallery.Find(id);
            if(photo != null)
           {
                
                System.IO.File.Delete(photo.Path);
                db.PhotoGallery.Remove(photo);
                db.SaveChanges();
            }
            return RedirectToAction("index");
        }
        
    }
}

BSATroop829/Controllers/LoggingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BSATroop829.Data;
using BSATroop829.Models;

namespace BSATroop829.Controllers
{
    public class LoggingController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LoggingController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Logging
        public async Task<IActionResult> Index()
        {
              return _context.LogEnties != null ? 
                          View(await _context.LogEnties.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.LogEnties'  is null.");
        }

        // GET: Logging/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.LogEnties == null)
            {
                return NotFound();
            }

            var loggingViewModel = await _context.LogEnties
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loggingViewModel == null)
            {
                return NotFound();
            }

            return View(loggingViewModel);
        }

        // GET: Logging/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Logging/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,User,Action,TimeStamp")] LoggingViewModel loggingViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(loggingViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(loggingViewModel);
        }

        // GET: Logging/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.LogEnties == null)
            {
                return NotFound();
            }

            var loggingViewModel = await _context.LogEnties.FindAsync(id);
            if (loggingViewModel == null)
            {
                return NotFound();
            }
            return View(loggingViewModel);
        }

        // POST: Logging/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,User,Action,TimeStamp")] LoggingViewModel loggingViewModel)
        {
            if (id != loggingViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loggingViewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoggingViewModelExists(loggingViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(loggingViewModel);
        }

        // GET: Logging/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LogEnties == null)
            {
                return NotFound();
            }

            var loggingViewModel = await _context.LogEnties
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loggingViewModel == null)
            {
                return NotFound();
            }

            return View(loggingViewModel);
        }

        // POST: Logging/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.LogEnties == null)
            {
                return Problem("Entity set 'ApplicationDbContext.LogEnties'  is null.");
            }
            var loggingViewModel = await _context.LogEnties.FindAsync(id);
            if (loggingViewModel != null)
            {
                _context.LogEnties.Remove(loggingViewModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoggingViewModelExists(int id)
        {
          return (_context.LogEnties?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BSATroop829/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BSATroop829.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }
    }
}

BSATroop829/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BSATroop829.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        public UsersController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var users = _userManager.Users;
            var allUsers = await _userManager.Users.ToListAsync();
            return View(allUsers);
        }
    }
}

BSATroop829/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BSATroop829</title>
    <link rel="stylesheet" href="~/css/bootswatchtheme.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/BSATroop829.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="shortcut icon" href="~/Favicon.ico" sizes="32x32" type="image/x-icon" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <img width="50" height="50" style="float:left" src="~/resources/scout_emblem.png" />
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">&nbsp; Troop 829</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("User"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle drop" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Boy Troop</a>
                                <div class="dropdown-menu" style="background-color:green">
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="BoyTroop">Home</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="BoyTroopCal">Calendar</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="BoyTroopOrgChartViewModels" asp-action="BoyTroopOrgChart">Organizational Chart</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="EventDueDates">Event Due Dates</a>
                                    @*<div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>*@
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Girl Troop</a>
                                <div class="dropdown-menu" style="background-color:green">
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="GirlTroop">Home</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="GirlTroopCal">Calendar</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="GirlTroopOrgChartViewModels" asp-action="GirlTroopOrgChart">Organizational Chart</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="EventDueDates">Event Due Dates</a>
                                    @*<div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>*@
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Activity Registration</a>
                                <div class="dropdown-menu" style="background-color:green">
                                    <a class="dropdown-item" asp-area="" asp-controller="SummerCamp" asp-action="Index">Summer Camp 2023</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="MeritBadgeCollegeRegistrationForm">Merit Badge College 2023</a>
                                    @*<div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>*@
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Requests</a>
                                <div class="dropdown-menu" style="background-color:green">
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="FinancialAidForm">Financial Aid Request</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="ReimbursementForm">Reimbursement Request</a>
                                    @*<div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>*@
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="TroopEagles" asp-action="Index">Eagles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="MeritBadgeCounselors" asp-action="Index">Local Merit Badge Counselors</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="FileManager" asp-action="Index">Documents</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="BandFeed" asp-action="Index">Band</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Informationals</a>
                                <div class="dropdown-menu" style="background-color:green">
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="FAQ">FAQ</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="ServiceHours">Service Hour Info</a>
                                    <a class="dropdown-item" style="color:orchid" href="https://my.scouting.org/VES/OnlineReg/1.0.0/?tu=UF-MB-205tab0829">GT REGISTRATION!</a>
                                    <a class="dropdown-item" style="color:aquamarine" href="https://my.scouting.org/VES/OnlineReg/1.0.0/?tu=UF-MB-205taa0829">BT REGISTRATION!</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" style="color:cyan" href="https://scoutbook.scouting.org">ScoutBook</a>
                                    <a class="dropdown-item" style="color:cyan"  href="https://my.scouting.org/">MyScouting</a>
                                    <a class="dropdown-item" style="color:cyan" href="https://lhcbsa.org/">Council</a>
                                    <a class="dropdown-item" style="color:cyan" href="https://lhcbsa.org/council/lincoln-trail/">District</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Gallery" asp-action="Index">Photo Gallery</a>
                            </li>
                            @if (User.IsInRole("Admin") || User.IsInRole("ScoutMaster") || User.IsInRole("Committee Member"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle drop" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
                                    <div class="dropdown-menu dropdown-menu-dark" style="background-color:green">
                                        <a class="dropdown-item" asp-area="" asp-controller="Roles" asp-action="Index">Manage Roles</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Index">Manage Users</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="BoyTroopOrgChartViewModels" asp-action="Index">Manage BT Org Chart</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="GirlTroopOrgChartViewModels" asp-action="Index">Manage GT Org Chart</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="Logging" asp-action="Index">View Logs</a>
                                    </div>
                                </li>
                            }
                        }
                        @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Boy Troop</a>
                        <div class="dropdown-menu">
                        <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="BoyTroop">Home</a>
                        <a class="dropdown-item" href="#">Calendar</a>
                        <a class="dropdown-item" href="#">Photos</a>
                        <a class="dropdown-item" href="#">Organizational Chart</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                        </li>*@
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - BSATroop829 - <a asp-area="" asp-controller="Home" asp-action="Credits">Credits</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js" integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous" async></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BSATroop829/Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]', 'Success');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]', 'Error');
    </script>
}