BSATroop829/Models/FileManagerViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace BSATroop829.Models
{
    public class FileManagerViewModel
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string? Name { get; set; }
        [StringLength(255)]
        public string? Path { get; set; }
        [StringLength(255)]
        public string? Type { get; set; }

        [NotMappedAttribute]
        [Required(ErrorMessage = "File is required.")]
        public List<IFormFile>? File { get; set; }
    }
}

BSATroop829/Controllers/FileManagerController.cs
using BSATroop829.Data;
using BSATroop829.Models;
using BSATroop829.Services;
using EllipticCurve.Utils;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using System.IO;

namespace BSATroop829.Controllers
{
    [Authorize]
    public class FileManagerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly LogService _logService;

        public FileManagerController(ApplicationDbContext context, LogService logService)
        {
            _context = context;
            _logService = logService;
        }

        // GET: FileManager
        public IActionResult Index()
        {
            FilesViewModel viewModel = new FilesViewModel();
            viewModel.FileList = _context.FileManager.ToList();
            viewModel.Files = new FileManagerViewModel();
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult AddFiles(FilesViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);
            var Files = model.Files.File;

            if (Files.Count > 0)
            {
                foreach (var item in Files)
                {
                    FileManagerViewModel currentFile = new FileManagerViewModel();
                    var guid = Guid.NewGuid().ToString();
                    var fileName = guid + "_" + item.FileName;
                    var filePath = "wwwroot/Resources/Files/" + fileName;
                    using (var stream = System.IO.File.Create(filePath))
                    {
                        item.CopyTo(stream);
                        currentFile.Name = fileName;
                        currentFile.Path = filePath;
                        _context.FileManager.Add(currentFile);
                        _context.SaveChanges();
                        _logService.Log(User.Identity.Name, "Added file " + currentFile.Name);
                    }
                }
                return RedirectToAction("Index");
            }


            return RedirectToAction("Index");
        }
        
        public IActionResult DeleteFile(int id)
        {
            var file = _context.FileManager.Find(id);
            if(file != null)
           {
                
                System.IO.File.Delete(file.Path);
                _context.FileManager.Remove(file);
                _context.SaveChanges();
                _logService.Log(User.Identity.Name, "removed file " + file.Name);
            }
            return RedirectToAction("index");
        }

        public IActionResult DownloadFile(int id)
        {
            var file = _context.FileManager.Find(id);
            if (file != null)
            {
                byte[] bytes = System.IO.File.ReadAllBytes(file.Path);
                return File(bytes, "application/octet-stream", file.Name.Split('_')[1]);
            }
            _logService.Log(User.Identity.Name, "downloaded file " + file.Name);
            return RedirectToAction("index");
        }

        private bool FileManagerViewModelExists(int id)
        {
          return (_context.FileManager?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

BSATroop829/Views/FileManager/Create.cshtml
@model BSATroop829.Models.FileManagerViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>FileManagerViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <input asp-for="Path" class="form-control" />
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BSATroop829/Views/FileManager/Delete.cshtml
@model BSATroop829.Models.FileManagerViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FileManagerViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BSATroop829/Views/FileManager/Details.cshtml
@model BSATroop829.Models.FileManagerViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>FileManagerViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Path)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Path)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BSATroop829/Views/FileManager/Edit.cshtml
@model BSATroop829.Models.FileManagerViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>FileManagerViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <input asp-for="Path" class="form-control" />
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

BSATroop829/Views/FileManager/Index.cshtml
@model FilesViewModel
@using BSATroop829.Helpers;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-12">
    <div class="card card-primary">
        <div class="card-header">
            <div class="card-title">
                <h1 class="text-center">Document Library</h1>
            </div>
        </div>
        <div class="card-body">
            @if (User.IsInRole("ScoutMaster") || User.IsInRole("Admin") || User.IsInRole("AsstScoutMaster") || User.IsInRole("Committee Member"))
            {
                <form id="frmDocumentLibrary" class="form-control" asp-action="AddFiles" asp-controller="FileManager" method="post" enctype="multipart/form-data">
                    <div class="col-md-6 col-sm-6">

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">File</label>

                            <div class="col-sm-6 custom-file">

                                <input asp-for="@Model.Files.File" type="file" class="form-control" multiple="multiple">
                                <span asp-validation-for="@Model.Files.File" class="text-danger"></span>

                            </div>
                            <div class="col-sm-4"> <button type="submit" class="btn btn-primary">Upload All</button></div>
                        </div>



                    </div>
                </form>
            }

            <br />
            <div class="row">
                @if (Model.FileList != null)
                {
                    foreach (var item in Model.FileList)
                    {
                        <div class="card card-img" style="height:25%">
                            <div class="card-img">
                                <h2>@item.Name.Split('_')[1].ToUpper()</h2>
                                @Html.ActionLink("Download", "DownloadFile", new { id = item.Id }, new {@class = "btn btn-primary", @style = "float:right"})
                                @if (User.IsInRole("ScoutMaster") || User.IsInRole("Admin") || User.IsInRole("AsstScoutMaster") || User.IsInRole("Committee Member"))
                                {
                                    <a href="@Url.Action("DeleteFile","FileManager",new { id=item.Id})" class="btn btn-secondary" style="float:right">Delete</a>
                                }
                            </div>
                        </div>
                    }

                }
            </div>
        </div>
    </div>
</div>